---
title: "GeoDataExploring"
author: "Karla Fettich"
date: "February 15, 2019"
output: html_document
---

```{r setup}

# load all packages needed

rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)

library(rgdal)
library(raster)
library(tmap)
library(dplyr)
library(tidyr)

```

Ok. Let's see what we can do with these data. 

## Load datasets

```{r import datasets}

# load geo data for nj & pa

nj <- readOGR(dsn="./Analyses/3_GIS/tl_2018_34_tract")
pa <- readOGR(dsn = "./Analyses/3_GIS/tl_2018_42_tract")
pa_nj <- rbind(nj,pa)

# load PetPoint

pp <- read.csv("./Data/petpoint.csv", stringsAsFactors = FALSE)
pp <- pp[!is.na(pp$INTPTLON),]  # get rid of geo NAs
pp.pa_nj <- pp[which(pp$GEOID %in% pa_nj$GEOID),]

# load application data dogs

dogs <- read.csv("./Data/dog_apps.csv", stringsAsFactors = FALSE)
dogs <- dogs[!is.na(dogs$INTPTLON),]  # get rid of geo NAs
dogs.pa_nj <- dogs[which(dogs$GEOID %in% pa_nj$GEOID),]

# load cards for dogs

dogcards <- read.csv("./Data/dog_cards.csv", stringsAsFactors = FALSE)
dogs.pa_nj <- merge(dogs.pa_nj, dogcards, by.x="outcome_trello_id", by.y="id")
dogs.pa_nj <- merge(dogs.pa_nj, pp.pa_nj, by="outcome_trello_id")
dogs.pa_nj <- dogs.pa_nj[dogs.pa_nj$species=="Dog",]

dogs.pa_nj$outcome_date <- as.POSIXlt(dogs.pa_nj$outcome_date, format="%m/%d/%Y %H:%M %p")
dogs.pa_nj$date_submitted <- as.POSIXlt(dogs.pa_nj$date_submitted, format="%m/%d/%Y")
dogs.pa_nj$time_to_adoption <- as.numeric(difftime(dogs.pa_nj$outcome_date,
                                        dogs.pa_nj$date_submitted,
                                        units="weeks"))

```

## Exploratory analyses

Where do adopters from Grays Ferry come from?

```{r explore}

# Grays Ferry

pp.gf <- pp.pa_nj[pp.pa_nj$species=="Dog" & pp.pa_nj$outcome_sitename=="Grays Ferry Avenue",] %>% 
  group_by(GEOID) %>%
  summarise(n=n())

pp.gf.spatial <-
  sp::merge(x = pa_nj, y = pp.gf, by = "GEOID")
pp.gf.spatial <- pp.gf.spatial[which(!is.na(pp.gf.spatial$n)), ]

tmap_mode("view")
tm_basemap("OpenStreetMap.BlackAndWhite") +
  tm_shape(pp.gf.spatial) + 
  tm_fill("n", palette = "Reds", alpha=0.85)

# PAC

pp.pac <- pp.pa_nj[pp.pa_nj$species=="Dog" & pp.pa_nj$outcome_sitename=="PAC",] %>% 
  group_by(GEOID) %>%
  summarise(n=n())

pp.pac.spatial <-
  sp::merge(x = pa_nj, y = pp.pac, by = "GEOID")
pp.pac.spatial <- pp.pac.spatial[which(!is.na(pp.pac.spatial$n)), ]

tmap_mode("view")
tm_basemap("OpenStreetMap.BlackAndWhite") +
  tm_shape(pp.pac.spatial) + 
  tm_fill("n", palette = "Reds", alpha=0.85)

# Grant Avenue

pp.ne <- pp.pa_nj[pp.pa_nj$species=="Dog" & pp.pa_nj$outcome_sitename=="Grant Avenue",] %>% 
  group_by(GEOID) %>%
  summarise(n=n())

pp.ne.spatial <-
  sp::merge(x = pa_nj, y = pp.ne, by = "GEOID")
pp.ne.spatial <- pp.ne.spatial[which(!is.na(pp.ne.spatial$n)), ]

tmap_mode("view")
tm_basemap("OpenStreetMap.BlackAndWhite") +
  tm_shape(pp.ne.spatial) + 
  tm_fill("n", palette = "Reds", alpha=0.85)

# PAWS Foster Program

pp.foster <- pp.pa_nj[pp.pa_nj$species=="Dog" & pp.pa_nj$outcome_sitename=="PAWS Foster Program",] %>% 
  group_by(GEOID) %>%
  summarise(n=n())

pp.foster.spatial <-
  sp::merge(x = pa_nj, y = pp.foster, by = "GEOID")
pp.foster.spatial <- pp.foster.spatial[which(!is.na(pp.foster.spatial$n)), ]

tmap_mode("view")
tm_basemap("OpenStreetMap.BlackAndWhite") +
  tm_shape(pp.foster.spatial) + 
  tm_fill("n", palette = "Reds", alpha=0.85)

# PAWS Offsite Adoptions

pp.offsite <- pp.pa_nj[pp.pa_nj$species=="Dog" & pp.pa_nj$outcome_sitename=="PAWS Offsite Adoptions",] %>% 
  group_by(GEOID) %>%
  summarise(n=n())

pp.offsite.spatial <-
  sp::merge(x = pa_nj, y = pp.offsite, by = "GEOID")
pp.offsite.spatial <- pp.offsite.spatial[which(!is.na(pp.offsite.spatial$n)), ]

tmap_mode("view")
tm_basemap("OpenStreetMap.BlackAndWhite") +
  tm_shape(pp.offsite.spatial) + 
  tm_fill("n", palette = "Reds", alpha=0.85)

```

Let's import household data.

```{r veteran info}
hh <- read.csv("/home/karla/Documents/RLadies/joys_fork/2019_datathon/Analyses/3_GIS/households_and_families/ACS_17_5YR_S1101_with_ann.csv",
                 stringsAsFactors = FALSE)
hh$GEO.id2 <- as.numeric(hh$GEO.id2)
pp.pa_nj.hh <- merge(pp.pa_nj, hh, by.x="GEOID", by.y="GEO.id2")
pp.pa_nj.hh$HC01_EST_VC03 <- as.numeric(pp.pa_nj.hh$HC01_EST_VC03) # estimated average household size
pp.pa_nj.hh$HC01_EST_VC28 <- as.numeric(pp.pa_nj.hh$HC01_EST_VC28) # estimate of units in structure, where multiple units
pp.pa_nj.hh$HC01_EST_VC02 <- as.numeric(pp.pa_nj.hh$HC01_EST_VC02) # total households

pp.hh <- pp.pa_nj.hh[pp.pa_nj.hh$species=="Dog",] %>% 
  group_by(GEOID) %>%
  summarise(n=n(), 
            est.hh.size=median(HC01_EST_VC03),
            est.units = median(HC01_EST_VC28),
            est.households = median(HC01_EST_VC02))

pp.hh.spatial <-
  sp::merge(x = pa_nj, y = pp.hh, by = "GEOID")
pp.hh.spatial <- pp.hh.spatial[which(!is.na(pp.hh.spatial$n)), ]

tmap_mode("view")
tm_basemap("OpenStreetMap.BlackAndWhite") +
  tm_shape(pp.hh.spatial) + 
  tm_fill("est.households", palette = "Reds", alpha=0.85)

cor.test(pp.hh.spatial$n, pp.hh.spatial$est.hh.size)
# the smaller the median households in the area, the more dog adopters

cor.test(pp.hh.spatial$n, pp.hh.spatial$est.units)
# the more units in structure, the more dog adopters

# let's see if this makes a difference by location; 

## Old City

pp.hh.loc <- pp.pa_nj.hh[pp.pa_nj.hh$species=="Dog" & pp.pa_nj.hh$outcome_sitename == "Grant Avenue",] %>% 
  group_by(GEOID) %>%
  summarise(n=n(), 
            est.hh.size=median(HC01_EST_VC03),
            est.units = median(HC01_EST_VC28),
            est.households = median(HC01_EST_VC02))

pp.hh.loc.spatial <-
  sp::merge(x = pa_nj, y = pp.hh.loc, by = "GEOID")
pp.hh.loc.spatial <- pp.hh.loc.spatial[which(!is.na(pp.hh.loc.spatial$n)), ]

tmap_mode("view")
tm_basemap("OpenStreetMap.BlackAndWhite") +
  tm_shape(pp.hh.loc.spatial) + 
  tm_fill("est.households", palette = "Reds", alpha=0.85)

cor.test(pp.hh.loc.spatial$n, pp.hh.loc.spatial$est.hh.size)
cor.test(pp.hh.loc.spatial$n, pp.hh.loc.spatial$est.units)
cor.test(pp.hh.loc.spatial$n, pp.hh.loc.spatial$est.households)

```

Ok; next we'll look at successful applications (either adopted or approved to adopt) and correlations to household variables.