---
title: "PAWS App-Trajectory Report"
author: "Ramaa Nathan"
date: "4/5/2019"
always_allow_html: yes
output: 
  github_document:
    toc: true 
    toc_depth: 4
    df_print: kable

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Executive Summary <span style="color:brown"> - Amy</span> (will wait until report is complete)

##Feature Engineering <span style="color:brown"> - Amy</span>
###Data Cleaning 
###Data Conversion
###Spreading/Creating to Indicator Variables
###Merging data


##Analysis of Time in Processing Applications
###How long does each application take?
###Heatmap 


##Application Characteristics 

### Affecting Adoption   <span style="color:brown"> - Ramaa </span> 
####Frequency of processing applications - is it daily checks or processing applications in bulk every few days?  (new analysis  -- to check)
####Budget, allergies, number of adults, number of children….

###Affecting Decline


##Data Issues affecting Analyses <span style="color:brown"> - Brendan </span>
###Missing Data
###Incorrect labels
###Recommendations for Collecting Clean Data

##Important Features for Prediction <span style="color:brown"> - Ramaa</span>


##Conclusions and Recommendations
###Recommendations to analyze the data frequently to check for improvements in processing application
###Suggest 
####How findings can be translated into concrete actions
####How data collection strategy should be improved
####How data analysis might be done on a regular basis
