---
title: "Cleaning Apps data"
author: "Amy Goodwin Davies"
always_allow_html: yes
output:
  github_document:
    toc: true
---

```{r setup, include = FALSE}
knitr::opts_knit$set(echo = T, message = F, warning = F, root.dir = "../../../")
```

```{r packages, echo = T,  message = F,  warning = T}
library(tidyverse)
library(lubridate)
library(plyr)
```

```{r scipen, echo = T,  message = F,  warning = T}
# Turn off scientific notation ----
options(scipen=999)
```

```{r source_functions, echo = T,  message = F,  warning = T}
# Source helper function(s) ----
source("Analyses/2_Applicants/helper_functions.R")
```

```{r read_data, echo = T,  message = F,  warning = T}
# Read data ----
cat_apps <- read_csv("Data/cat_apps.csv")
dog_apps <- read_csv("Data/dog_apps.csv")
```

```{r structure, echo = T,  message = F,  warning = T}
# Structure ----
colnames(cat_apps)
nrow(cat_apps)
head(cat_apps)
summary(cat_apps)

colnames(dog_apps)
nrow(dog_apps)
head(dog_apps)
summary(dog_apps)

cat_apps$animal_type <- "cat"
dog_apps$animal_type <- "dog"
apps <- rbind(cat_apps, dog_apps)
colnames(apps)
nrow(apps)
head(apps)
summary(apps)
```
```{r begin_cleaning, echo = T,  message = F,  warning = T}
# Cleaning up each variable ----
apps_clean <- apps
```

```{r animal_type, echo = T,  message = F,  warning = T}
# .... apps_clean$animal_type ----
str(apps_clean$animal_type)
unique(apps_clean$animal_type)
apps_clean$animal_type <- as.factor(apps_clean$animal_type)
dput(summary(apps_clean$animal_type))

```

```{r X1, echo = T,  message = F,  warning = T}
# .... apps_clean$X1 ----
str(apps_clean$X1)
unique(apps_clean$X1)[1:5]
apps_clean <- subset(apps_clean, select = -c(X1))
colnames(apps_clean)
```

```{r duplicates, echo = T,  message = F,  warning = T}
# Duplicates ----
all(duplicated(apps_clean) == FALSE) # duplicate rows...

```

```{r date_submitted, echo = T,  message = F,  warning = T}
# .... apps_clean$date_submitted ----
str(apps_clean$date_submitted)
apps_clean$date_submitted <- mdy(apps_clean$date_submitted)
str(apps_clean$date_submitted)
ggplot(apps_clean, aes(x = wday(date_submitted, label = TRUE))) +
  geom_bar()
ggplot(apps_clean, aes(x = month(date_submitted, label = TRUE))) +
  geom_bar()
ggplot(apps_clean, aes(x = date_submitted)) +
  geom_histogram(binwidth = 1)
summary(apps_clean$date_submitted)
paste(min(apps_clean$date_submitted), max(apps_clean$date_submitted), sep = " to ")

```

```{r ideal_adoption_timeline, echo = T,  message = F,  warning = T}
# .... apps_clean$ideal_adoption_timeline ----
str(apps_clean$ideal_adoption_timeline)
unique(apps_clean$ideal_adoption_timeline)
apps_clean$ideal_adoption_timeline <- gsub("next-few-weeks", "few-weeks", apps_clean$ideal_adoption_timeline)
unique(apps_clean$ideal_adoption_timeline)
apps_clean$ideal_adoption_timeline <- as.factor(apps_clean$ideal_adoption_timeline)
str(apps_clean$ideal_adoption_timeline)
summary(apps_clean$ideal_adoption_timeline)
dput(levels(apps_clean$ideal_adoption_timeline))

```

```{r reason_for_adoption, echo = T,  message = T,  warning = T}
# .... apps_clean$reason_for_adoption ----
apps_clean <- apps
str(apps_clean$reason_for_adoption)
summary(apps_clean$reason_for_adoption)
unique(apps_clean$reason_for_adoption)
apps_clean$reason_for_adoption <- gsub("it-s-a-surprise", "a-surprise", apps_clean$reason_for_adoption)
dput(get_unique_elements(apps_clean, "reason_for_adoption"))
reason_for_adoption_tidy <- tidy_elements(apps_clean, "reason_for_adoption")
apps_clean <- reason_for_adoption_tidy$output_df
reason_for_adoption_elements <- reason_for_adoption_tidy$elements
reason_for_adoption_new_colnames <- reason_for_adoption_tidy$new_colnames
reason_for_adoption_elements_summary <- reason_for_adoption_tidy$elements_summary
ggplot(reason_for_adoption_elements_summary, aes(x = fct_reorder(reason_for_adoption, count), y = count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = count), vjust = -0.25, position = "identity", size = 2.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill=FALSE)

```

```{r specific_animal, echo = T,  message = F,  warning = T}
# .... apps_clean$specific_animal ----
str(apps_clean$specific_animal)
dput(summary(apps_clean$specific_animal))

```

```{r adults_in_home, echo = T,  message = F,  warning = T}
# .... apps_clean$adults_in_home ----
summary(apps_clean$adults_in_home) # should change to numeric
apps_clean$adults_in_home <- gsub("^-", "", apps_clean$adults_in_home) # get rid of "-"
apps_clean$adults_in_home <- word(apps_clean$adults_in_home,1) # get first word
unique(apps_clean$adults_in_home)
apps_clean$adults_in_home <- as.numeric(as.character(apps_clean$adults_in_home))
ggplot(apps_clean, aes(x = adults_in_home)) +
  geom_histogram(binwidth = 1)
str(apps_clean$adults_in_home)
apps_clean$adults_in_home <- replace(apps_clean$adults_in_home,
                                       apps_clean$adults_in_home > 15,
                                       NA)
ggplot(apps_clean, aes(x = adults_in_home)) +
  geom_histogram(binwidth = 1)
summary(apps_clean$adults_in_home)
dput(summary(apps_clean$adults_in_home))

```

* Remove negative numbers and greater than 15

```{r children_in_home, echo = T,  message = F,  warning = T}
# .... apps_clean$children_in_home ----
summary(apps_clean$children_in_home) # should change to numeric
apps_clean$children_in_home <- gsub("^-", "", apps_clean$children_in_home) # get rid of "-"
apps_clean$children_in_home <- word(apps_clean$children_in_home,1) # get first word
unique(apps_clean$children_in_home)
apps_clean$children_in_home <- as.numeric(as.character(apps_clean$children_in_home))
ggplot(apps_clean, aes(x = children_in_home)) +
  geom_histogram(binwidth = 1)
apps_clean$children_in_home <- replace(apps_clean$children_in_home,
                                       apps_clean$children_in_home > 15,
                                       NA)
ggplot(apps_clean, aes(x = children_in_home)) +
  geom_histogram(binwidth = 1)
summary(apps_clean$children_in_home)
dput(summary(apps_clean$children_in_home))

```

* Remove negative numbers and greater than 15

```{r all_household_agree, echo = T,  message = F,  warning = T}
# .... apps_clean$all_household_agree ----
str(apps_clean$all_household_agree)
summary(apps_clean$all_household_agree)
unique(apps_clean$all_household_agree)
apps_clean$all_household_agree <- gsub("it-s-a-surprise", "a-surprise", apps_clean$all_household_agree)
dput(get_unique_elements(apps_clean, "all_household_agree"))
all_household_agree_tidy <- tidy_elements(apps_clean, "all_household_agree")
apps_clean <- all_household_agree_tidy$output_df
all_household_agree_elements <- all_household_agree_tidy$elements
all_household_agree_new_colnames <- all_household_agree_tidy$new_colnames
all_household_agree_elements_summary <- all_household_agree_tidy$elements_summary
ggplot(all_household_agree_elements_summary, aes(x = fct_reorder(all_household_agree, count), y = count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = count), vjust = -0.25, position = "identity", size = 2.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill=FALSE)

```

```{r allergies, echo = T,  message = F,  warning = T}
# .... apps_clean$allergies ----
str(apps_clean$allergies)
summary(apps_clean$allergies)
unique(apps_clean$allergies)
dput(get_unique_elements(apps_clean, "allergies"))
allergies_tidy <- tidy_elements(apps_clean, "allergies")
apps_clean <- allergies_tidy$output_df
allergies_elements <- allergies_tidy$elements
allergies_new_colnames <- allergies_tidy$new_colnames
allergies_elements_summary <- allergies_tidy$elements_summary
ggplot(allergies_elements_summary, aes(x = fct_reorder(allergies, count), y = count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = count), vjust = -0.25, position = "identity", size = 2.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill=FALSE)

```

```{r home_owner, echo = T,  message = F,  warning = T}
# .... apps_clean$home_owner ----
str(apps_clean$home_owner)
summary(apps_clean$home_owner)
unique(apps_clean$home_owner)
apps_clean$home_owner <- as.factor(apps_clean$home_owner)
summary(apps_clean$home_owner)
dput(levels(apps_clean$home_owner))

```

```{r home_pet_policy, echo = T,  message = F,  warning = T}
# .... apps_clean$home_pet_policy ----
str(apps_clean$home_pet_policy)
summary(apps_clean$home_pet_policy)
apps_clean$home_pet_policy <- gsub("no-yet", "not-yet", apps_clean$home_pet_policy)
apps_clean[apps_clean$home_pet_policy == "not-applicable" & 
             !is.na(apps_clean$home_pet_policy) |
             apps_clean$home_pet_policy == "n-a" & 
             !is.na(apps_clean$home_pet_policy),]$home_pet_policy <- NA
unique(apps_clean$home_pet_policy)
apps_clean$home_pet_policy <- as.factor(apps_clean$home_pet_policy)
summary(apps_clean$home_pet_policy)
dput(levels(apps_clean$home_pet_policy))

```

```{r experience, echo = T,  message = F,  warning = T}
# .... apps_clean$experience ----
str(apps_clean$experience)
summary(apps_clean$experience)
length(unique(apps_clean$experience))
dput(get_unique_elements(apps_clean, "experience"))
experience_tidy <- tidy_elements(apps_clean, "experience")
apps_clean <- experience_tidy$output_df
experience_elements <- experience_tidy$elements
experience_new_colnames <- experience_tidy$new_colnames
experience_elements_summary <- experience_tidy$elements_summary
ggplot(experience_elements_summary, aes(x = fct_reorder(experience, count), y = count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = count), vjust = -0.25, position = "identity", size = 2.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill=FALSE)

```

```{r budget_monthly, echo = T,  message = F,  warning = T}
# .... apps_clean$budget_monthly ----
str(apps_clean$budget_monthly)
summary(apps_clean$budget_monthly)
unique(apps_clean$budget_monthly)
apps_clean$budget_monthly <- gsub("[$]|[(]|[)]|[,]", "", apps_clean$budget_monthly)
apps_clean$budget_monthly <- gsub("^-", "", apps_clean$budget_monthly)
unique(apps_clean$budget_monthly)
apps_clean$budget_monthly <- as.numeric(as.character(apps_clean$budget_monthly))
ggplot(apps_clean, aes(x = budget_monthly)) +
  geom_histogram(binwidth = 50) +
  xlim(0,50000)
apps_clean$budget_monthly <- replace(apps_clean$budget_monthly,
                                       apps_clean$budget_monthly > 5000,
                                       NA)
ggplot(apps_clean, aes(x = budget_monthly)) +
  geom_histogram(binwidth = 50) +
  xlim(0,5000)
unique(apps_clean$budget_monthly)
dput(summary(apps_clean$budget_monthly))

```

```{r budget_emergency, echo = T,  message = F,  warning = T}
# .... apps_clean$budget_emergency ----
str(apps_clean$budget_emergency)
summary(apps_clean$budget_emergency)
unique(apps_clean$budget_emergency)
apps_clean$budget_emergency <- gsub("[$]|[(]|[)]|[,]", "", apps_clean$budget_emergency)
apps_clean$budget_emergency <- gsub("^-", "", apps_clean$budget_emergency)
unique(apps_clean$budget_emergency)
apps_clean$budget_emergency <- as.numeric(as.character(apps_clean$budget_emergency))
ggplot(apps_clean, aes(x = budget_emergency)) +
  geom_histogram(binwidth = 50)+
  xlim(0,100000)
apps_clean$budget_emergency <- replace(apps_clean$budget_emergency,
                                       apps_clean$budget_emergency > 10000,
                                       NA)
ggplot(apps_clean, aes(x = budget_emergency)) +
  geom_histogram(binwidth = 50) +
  xlim(0,10000)
unique(apps_clean$budget_emergency)
dput(summary(apps_clean$budget_emergency))

```

```{r home_alone_avg, echo = T,  message = F,  warning = T}
# .... apps_clean$home_alone_avg ----
str(apps_clean$home_alone_avg)
summary(apps_clean$home_alone_avg)
unique(apps_clean$home_alone_avg)
apps_clean$home_alone_avg <- trimws(gsub("h", "", apps_clean$home_alone_avg))
apps_clean$home_alone_avg <- as.numeric(as.character(apps_clean$home_alone_avg))
ggplot(apps_clean, aes(x = home_alone_avg)) +
  geom_histogram(binwidth = 1)
unique(apps_clean$home_alone_avg)
dput(summary(apps_clean$home_alone_avg))

```

```{r home_alone_max, echo = T,  message = F,  warning = T}
# .... apps_clean$home_alone_max ----
str(apps_clean$home_alone_max)
summary(apps_clean$home_alone_max)
unique(apps_clean$home_alone_max)
apps_clean$home_alone_max <- trimws(gsub("h", "", apps_clean$home_alone_max))
apps_clean$home_alone_max <- as.numeric(as.character(apps_clean$home_alone_max))
ggplot(apps_clean, aes(x = home_alone_max)) +
  geom_histogram(binwidth = 1)
unique(apps_clean$home_alone_max)
dput(summary(apps_clean$home_alone_max))

```

```{r pet_kept, echo = T,  message = F,  warning = T}
# .... apps_clean$pet_kept ----
str(apps_clean$pet_kept)
summary(apps_clean$pet_kept)
length(unique(apps_clean$pet_kept))
apps_clean$pet_kept <- gsub("unsupervised-access-to-my-yard-9doggie-door-etc",
                            "unsupervised-access-to-my-yard-doggie-door-etc",
                            apps_clean$pet_kept)
dput(get_unique_elements(apps_clean, "pet_kept"))
pet_kept_tidy <- tidy_elements(apps_clean, "pet_kept")
apps_clean <- pet_kept_tidy$output_df
pet_kept_elements <- pet_kept_tidy$elements
pet_kept_new_colnames <- pet_kept_tidy$new_colnames
pet_kept_elements_summary <- pet_kept_tidy$elements_summary
ggplot(pet_kept_elements_summary, aes(x = fct_reorder(pet_kept, count), y = count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = count), vjust = -0.25, position = "identity", size = 2.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill=FALSE)

```

```{r exercise, echo = T,  message = F,  warning = T}
# .... apps_clean$exercise ----
str(apps_clean$exercise)
summary(apps_clean$exercise)
length(unique(apps_clean$exercise))
dput(get_unique_elements(apps_clean, "exercise"))
exercise_tidy <- tidy_elements(apps_clean, "exercise")
apps_clean <- exercise_tidy$output_df
exercise_elements <- exercise_tidy$elements
exercise_new_colnames <- exercise_tidy$new_colnames
exercise_elements_summary <- exercise_tidy$elements_summary
ggplot(exercise_elements_summary, aes(x = fct_reorder(exercise, count), y = count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = count), vjust = -0.25, position = "identity", size = 2.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill=FALSE)

```

```{r needs, echo = T,  message = F,  warning = T}
# .... apps_clean$needs ----
str(apps_clean$needs)
summary(apps_clean$needs)
length(unique(apps_clean$needs))
dput(get_unique_elements(apps_clean, "needs"))
needs_tidy <- tidy_elements(apps_clean, "needs")
apps_clean <- needs_tidy$output_df
needs_elements <- needs_tidy$elements
needs_new_colnames <- needs_tidy$new_colnames
needs_elements_summary <- needs_tidy$elements_summary
ggplot(needs_elements_summary, aes(x = fct_reorder(needs, count), y = count)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = count), vjust = -0.25, position = "identity", size = 2.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill=FALSE)

```

```{r return_pet, echo = T,  message = F,  warning = T}
# .... apps_clean$return_pet ----
str(apps_clean$return_pet)
summary(apps_clean$return_pet)
length(unique(apps_clean$return_pet))
dput(get_unique_elements(apps_clean, "return_pet"))
return_pet_tidy <- tidy_elements(apps_clean, "return_pet")
apps_clean <- return_pet_tidy$output_df
return_pet_elements <- return_pet_tidy$elements
return_pet_new_colnames <- return_pet_tidy$new_colnames
return_pet_elements_summary <- return_pet_tidy$elements_summary
ggplot(return_pet_elements_summary, aes(x = fct_reorder(return_pet, count), y = count)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = count), vjust = -0.25, position = "identity", size = 2.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill=FALSE)

```

```{r how_heard, echo = T,  message = F,  warning = T}
# .... apps_clean$how_heard ----
str(apps_clean$how_heard)
summary(apps_clean$how_heard)
unique(apps_clean$how_heard)
dput(get_unique_elements(apps_clean, "how_heard"))
how_heard_tidy <- tidy_elements(apps_clean, "how_heard")
apps_clean <- how_heard_tidy$output_df
how_heard_elements <- how_heard_tidy$elements
how_heard_new_colnames <- how_heard_tidy$new_colnames
how_heard_elements_summary <- how_heard_tidy$elements_summary
ggplot(how_heard_elements_summary, aes(x = fct_reorder(how_heard, count), y = count)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = count), vjust = -0.25, position = "identity", size = 2.5) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(fill=FALSE)

```

```{r id, echo = T,  message = F,  warning = T}
# .... apps_clean$outcome_trello_id ----
str(apps_clean$outcome_trello_id)
summary(apps_clean$outcome_trello_id)
nrow(apps_clean[is.na(apps_clean$outcome_trello_id),])
length(unique(apps_clean$outcome_trello_id))
id_summary <- ddply(apps_clean, .(outcome_trello_id), summarise,
                    id_count = length(outcome_trello_id))
id_summary[is.na(id_summary$outcome_trello_id),]
id_summary <- subset(id_summary, !is.na(outcome_trello_id))
id_summary_2 <- ddply(id_summary, .(id_count), summarise,
                      num_ids_with_count = length(outcome_trello_id))
id_summary_2

```

```{r geo_variables, echo = T,  message = F,  warning = T}
# .... apps_clean$STATEFP ----
str(apps_clean$STATEFP)
summary(apps_clean$STATEFP)
unique(apps_clean$STATEFP)
apps_clean$STATEFP <- as.factor(apps_clean$STATEFP)
summary(apps_clean$STATEFP)

# .... apps_clean$COUNTYFP ----
str(apps_clean$COUNTYFP)
summary(apps_clean$COUNTYFP)
unique(apps_clean$COUNTYFP)
apps_clean$COUNTYFP <- as.factor(apps_clean$COUNTYFP)
summary(apps_clean$COUNTYFP)

# .... apps_clean$TRACTCE ----
str(apps_clean$TRACTCE)
summary(apps_clean$TRACTCE)
length(unique(apps_clean$TRACTCE))
apps_clean$TRACTCE <- as.factor(apps_clean$TRACTCE)
summary(apps_clean$TRACTCE)

# .... apps_clean$TRACTCE ----
str(apps_clean$GEOID)
summary(apps_clean$GEOID)
length(unique(apps_clean$GEOID))
apps_clean$GEOID <- as.factor(apps_clean$GEOID)
summary(apps_clean$GEOID)

# .... apps_clean$NAME ----
str(apps_clean$NAME)
summary(apps_clean$NAME)
length(unique(apps_clean$NAME))
apps_clean$NAME <- as.factor(apps_clean$NAME)
summary(apps_clean$NAME)

# .... apps_clean$NAMELSAD ----
str(apps_clean$NAMELSAD)
summary(apps_clean$NAMELSAD)
unique(apps_clean$NAMELSAD)[1:5]
apps_clean$NAMELSAD <- trimws(gsub("Census Tract", "", apps_clean$NAMELSAD))
length(unique(apps_clean$NAMELSAD))
apps_clean$NAMELSAD <- as.factor(apps_clean$NAMELSAD)
summary(apps_clean$NAMELSAD)

# .... apps_clean$MTFCC ----
str(apps_clean$MTFCC)
summary(apps_clean$MTFCC)
length(unique(apps_clean$MTFCC))
apps_clean$MTFCC <- as.factor(apps_clean$MTFCC)
summary(apps_clean$MTFCC)

# .... apps_clean$FUNCSTAT ----
str(apps_clean$FUNCSTAT)
summary(apps_clean$FUNCSTAT)
length(unique(apps_clean$FUNCSTAT))
apps_clean$FUNCSTAT <- as.factor(apps_clean$FUNCSTAT)
summary(apps_clean$FUNCSTAT)

# .... apps_clean$ALAND ----
str(apps_clean$ALAND)
summary(apps_clean$ALAND)
length(unique(apps_clean$ALAND))
apps_clean$ALAND <- as.factor(apps_clean$ALAND)
summary(apps_clean$ALAND)

# .... apps_clean$AWATER ----
str(apps_clean$AWATER)
summary(apps_clean$AWATER)
length(unique(apps_clean$AWATER))
apps_clean$AWATER <- as.factor(apps_clean$AWATER)
summary(apps_clean$AWATER)

# .... apps_clean$INTPTLAT ----
str(apps_clean$INTPTLAT)
length(summary(apps_clean$INTPTLAT))
ggplot(apps_clean, aes(x = INTPTLAT)) +
  geom_histogram(binwidth = 0.1)

# .... apps_clean$INTPTLON ----
str(apps_clean$INTPTLON)
summary(apps_clean$INTPTLON)
ggplot(apps_clean, aes(x = INTPTLON)) +
  geom_histogram(binwidth = 0.1)

```

```{r city, echo = T,  message = F,  warning = T}
# .... apps_clean$City ---- 
str(apps_clean$City)
summary(apps_clean$City)
apps_clean$City <- toupper(apps_clean$City)
apps_clean$City <- gsub("[.]|[,]| PA$", "", apps_clean$City)
apps_clean$City <- trimws(gsub("  ", " ", apps_clean$City))
apps_clean$City <- gsub("MT ", "MOUNT ", apps_clean$City)
apps_clean$City <- gsub("19010", "BRYN MAWR", apps_clean$City)
apps_clean$City <- gsub("CHETSER", "CHESTER", apps_clean$City)
apps_clean$City <- gsub("ROYERFORD", "ROYERSFORD", apps_clean$City)
apps_clean$City <- gsub("NORTH WHALES", "NORTH WALES", apps_clean$City)
apps_clean$City <- gsub("MONTGOMERY VALLAGE", "MONTGOMERY VILLAGE", apps_clean$City)
apps_clean$City <- gsub("E LANSDOWNE", "EAST LANSDOWNE", apps_clean$City)
apps_clean$City <- gsub("PHILLY|FILADELFIA|PHILIDELPHIA|PHIMADELPHIA|PHIALADELPHIA|PHIALDELPHIA|PHILDELPHIA", "PHILADELPHIA", apps_clean$City)
apps_clean[startsWith(apps_clean$City, "PHILA"),]$City <- "PHILADELPHIA"
apps_clean$City <- replace(apps_clean$City,
                           apps_clean$City %in% c("Y"),
                           NA)
sort(unique(apps_clean$City))
apps_clean$City <- as.factor(apps_clean$City)
summary(apps_clean$City)
apps_clean %>% 
  group_by(City) %>% 
  tally() %>% 
  ungroup(City) %>% 
  filter(n > 5 ) %>% 
  ggplot(aes(x = fct_reorder(City, n), y = n)) +
    geom_bar(stat = "identity") +
    coord_flip() +
  geom_text(aes(label = n), vjust = 0.25, hjust = -0.25, position = "identity", size = 2.5) +
  guides(fill=FALSE)

```

```{r state, echo = T,  message = F,  warning = T}
# .... apps_clean$State ----
str(apps_clean$State)
summary(apps_clean$State)
unique(apps_clean$State)
apps_clean$State <- as.factor(apps_clean$State)
summary(apps_clean$State)

```


```{r zip, echo = T,  message = F,  warning = T}
# .... apps_clean$ZIP ----
str(apps_clean$ZIP)
summary(apps_clean$ZIP)
apps_clean$ZIP <- if_else(nchar(apps_clean$ZIP) == 4,
                          paste0("0",apps_clean$ZIP),
                          apps_clean$ZIP)
apps_clean$ZIP <- str_extract(apps_clean$ZIP, "^.{5}")
length(unique(apps_clean$ZIP))
apps_clean$ZIP <- as.factor(apps_clean$ZIP)
summary(apps_clean$ZIP)

```

```{r X1_2, echo = T,  message = F,  warning = T}
# .... apps_clean$X1 ----
str(apps_clean$X1)
unique(apps_clean$X1)[1:5]
apps_clean <- subset(apps_clean, select = -c(X1))

```

```{r duplicates_2, echo = T,  message = F,  warning = T}
# Duplicates ----
all(duplicated(apps_clean) == FALSE)
nrow(apps_clean[duplicated(apps_clean),])
nrow(apps_clean[is.na(apps_clean$outcome_trello_id) & apps_clean$date_submitted == "12/18/2018" & apps_clean$GEOID == "34021002800",])

```

```{r missing, echo = T,  message = F,  warning = T}
# Structure ----
colSums(is.na(apps_clean))
```
```{r structure_2, echo = T,  message = F,  warning = T}
# Structure ----
nrow(apps_clean)
head(apps_clean)
str(apps_clean)
summary(apps_clean)
colnames(apps_clean)
```



```{r subset_columns, echo = T,  message = F,  warning = T}
# Write cleaned data ----
apps_clean <- select(apps_clean, c(date_submitted, ideal_adoption_timeline,
                                   reason_for_adoption, specific_animal,
                                   adults_in_home, children_in_home,
                                   all_household_agree, allergies,
                                   home_owner, home_pet_policy,
                                   experience, budget_monthly,
                                   budget_emergency, home_alone_avg,
                                   home_alone_max, pet_kept,
                                   exercise, needs, return_pet,
                                   how_heard, outcome_trello_id,
                                   City, State,
                                   ZIP, animal_type))
```

```{r write_data, echo = T,  message = F,  warning = T}
# Write cleaned data ----
write_csv(apps_clean, "Analyses/2_Applicants/amygood/output/apps_clean.csv")
```
